### ISSUE TITLE
Need to Move Current Existing Attributes Checks from routers.py to models.py

### ISSUE THREAD

**Issue by benno0810** [DevOps-Sum22-Inventory-Squad/inventory#35]
**As a product owner 
 **I need** to refactor the current code to follow the MVC style
 **So that** attribute validation is maintained only in the models
   
 ### Details and Assumptions
 * implemented attributes appear in the router.py
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given any restful API call
 When all attribute validation needs to be handled in models
 Then routers will only handle user interface jobs

**Comment by wsrong97** [comment]
You had a lot of business logic in your Flask Controller, which should have been in the model. If you notice, my sample code does all attribute checking the the deserialize() method which would eliminate all of if/then/else code in your Flask controller. Try and move this to the model to make your Flask app cleaner. —feedback from John

**Comment by DariaXu** [comment]
In testing, when when I POST JSON data under /localhost:8000/inventories with condition field =0, internal server error occurs. Need to check such case before creating a new inventory to prevent.

**Comment by DariaXu** [comment]
Given POST JSON to `/localhost:8000/inventories` 
When condition field =0 in the JSON file 
Then return error
