### ISSUE TITLE
Need a service that reads the number of an inventory item

### ISSUE THREAD

**Issue by benno0810** [DevOps-Sum22-Inventory-Squad/inventory#4]
**As a** order managing specialist  
 **I need** to inspect if an item of a  requested order is available or not
 **So that** this requested order can be filled
   
 ### Details and Assumptions
* This service is RESTFUL and will respond to a GET query.
* According to the HTTP query will generate SQL query(or database API) to the database.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given an inventory information query service
 When I call GET /inventory/*itemID 
 Then will return successful code "200" or failing code "400"
 Then will look for the item ID in the item database and return the item quantity, restock level status, and condition.
 ```

**Comment by wsrong97** [comment]
Hi Jianze, is your story  related to the 'read a resource' function, if so I think rename the story as 'Need a service that reads the number of an inventory item' might be more clear. What's your opinion?@benno0810

**Comment by benno0810** [comment]
the number of an inventory and availability of inventory sometimes have different meanings and need to create 2 services to the requests respectively.  
E.g specialists send an order containing:

`{order_id: 12345, item_A:10, item_B:11}`
we reply:
`{A:9, B:11}`
he will need to calculate by himself at the front end or on the client whether this order can be fulfilled. If we reply something like 
`{this order id is available}` then this order is automatically considered fulfilled (or pre-occupied) and he can send another request to update the inventory with order info without any further calculation.
is it reasonable or possible to happen? @wsrong97

**Comment by wsrong97** [comment]
As stated in the homework, our instructor suggests **at least** what our microservices would be able to provide.

_The primary requirement for creating these microservices is that they must be RESTful
according to the guidelines that we will learn in class. **Initially** each microservices must
support the complete Create, Read, Update, & Delete (CRUD) lifecycle calls plus List (5
API calls in all)._ 

So apart from these services, we can create more based on need in the course of our agile development.

**Comment by wsrong97** [comment]
You are right, the number of an item is different from the availability of an item. So we need separate stories. I think the availability of the service can be provided based on **Read service** if already implemented.

**Comment by benno0810** [comment]
@wsrong97 it comes to me that we might not know the details inside an order because we don't have access to the order database or order cache, in this case, a query to us should only contain some separate item IDs, so the status for an order is not in our hands so far (but the inventory information we must handle).

**Comment by wsrong97** [comment]
> @wsrong97 it comes to me that we might not know the details inside an order because we don't have access to the order database or order cache, in this case, a query to us should only contain some separate item IDs, so the status for an order is not in our hands so far (but the inventory information we must handle).

I guess so,  I don't know the entire design of this eCommerce services. I think in reality, different microservices must rely on each other to provide higher level functions. But how to interact with services that other squad groups are aimed to provide, is outside the aim of our squad.
