### ISSUE TITLE
Need code refactoring for the create and list service

### ISSUE THREAD

**Issue by wangpengda1210** [DevOps-Sum22-Inventory-Squad/inventory#40]
**As a** developer
 **I need** code refactoring for the create service
 **So that** the create service can run correctly on the new database model
   
 ### Details and Assumptions
 * The API must be RESTful and respond to a POST query.
 * When creating an item, you must specify the product_id and condition in the request body.
 * Duplicate product_id and condition combination must return a conflict error code.
 * If the item is successfully created, return 201 created code and the location header.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given there is no inventory item with product_id "1" and condition "1"
 When I call “GET /inventories” with product_id "1" and condition "1" in the request body
 Then a new inventory item with product_id "1" and condition "1" should be created
 ```

**Comment by DariaXu** [comment]
Fixed:
You had a lot of business logic in your Flask Controller, which should have been in the model. If you notice, my sample code does all attribute checking the the deserialize() method which would eliminate all of if/then/else code in your Flask controller. Try and move this to the model to make your Flask app cleaner. —feedback from John

**Comment by DariaXu** [comment]
Fixed:
In testing, when when I POST JSON data under /localhost:8000/inventories with condition field =0, internal server error occurs. Need to check such case before creating a new inventory to prevent.
