### ISSUE TITLE
Need to manage our inventory information

### ISSUE THREAD

**Issue by wsrong97** [DevOps-Sum22-Inventory-Squad/inventory#5]
**As a** Product Owner
 **I need** to manage our inventory information.
 **So that** we will have knowledge of the number of each product we have.
   
 ### Details and Assumptions
 * Choose a database like PostgreSQL to manage our inventory information. 
As our final goal is to provide functions like (CRUD + list)
• Create a Resource
• Read a Resource
• Update a Resource
• Delete a Resource
• List Resources
to users, which are always the same. 
We can use a layered design for the whole implementation just like **the counter service example in the lecture**.  That is, these above functions are based on APIs our database model provides. 

 * So we need to provide basic APIs for these above functions. I think the followings are sufficient.
• initialize[Initializes the database]
• find[to find whether an item is present or not]
• list[what kind of items we have]
• add[add new items to our inventory]
• delete[an item is sold out and we don't sell it anymore]
• update[set the number of the item to a certain value] 

 ### Acceptance Criteria  
   Provide APIs for implementing RESTful services.
 ```gherkin
 Given a database model
 When asked to provide "CRUD and list" and relevant services
 Then these services can be easily implemented by basic APIs our database model provides.
 ```

**Comment by wentau** [comment]
Closed due to splitting into smaller stories.

**Comment by wentau** [comment]
Closed due to its been split into smaller stories.
