### ISSUE TITLE
Need to add UI to List all inventories

### ISSUE THREAD

**Issue by wentau** [DevOps-Sum22-Inventory-Squad/inventory#60]
**As an** inventory manager
 **I need** a UI for List
 **So that** I could see all the inventory items currently recorded
   
 ### Details and Assumptions
 * We will use the sample UI code in `lab-flask-bdd` as an example
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I am the inventory manager
 When I go to the "Inventory Home Page" - "/inventories"
 Then I should see a list of items currently in my inventory
 ```

**Comment by wsrong97** [comment]
As the query method is part of the List method, so a single button with two functionalities is enough. But BDD testing must test two behaviors. So two stories.
Another way is to use two buttons, one List button and another one is Query button. 
The difference in content and style and interactive logic between these two is slightly different
