### ISSUE TITLE
Need to create documentation for Create Inventory service

### ISSUE THREAD

**Issue by benno0810** [DevOps-Sum22-Inventory-Squad/inventory#76]
**As a** Product Owner
 **I need** to use Swagger to create interactive documentation for Create Inventory
 **So that** REST API can be referred and tested in link BASE_URL+ /apidocs/
   
 ### Details and Assumptions
 * There is a home page with UI for Inventory service.
 * Create service is written with Flask-RESTX
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a REST API for creating an inventory item
 When entering link BASE_URL + /apidocs/ on Home Page
 Then Usage of the API is explained and can be interactively tested in the sub-page.
 ```

**Comment by wangpengda1210** [comment]
Duplicate with #75
