### ISSUE TITLE
Need a service to create an inventory item

### ISSUE THREAD

**Issue by DariaXu** [DevOps-Sum22-Inventory-Squad/inventory#8]
**As a** Inventory Manager
 **I need** the ability to create a new inventory item
 **So that**  I can track this new item

 ### Details and Assumptions
- The API must be RESTful and respond to a POST query.
- When creating an item, you must specify the item ID and the product ID in the path.
(If the item's information(condition, restock levels, etc.) is not specified in the path, set them to the default value.)
- Duplicate IDs must return a conflict error code.
- If the storage has already reached the maximum, return an error code.
- If the item is successfully created, return 201 created code and the location header.
   
 ### Acceptance Criteria  

 ```gherkin
 Given the inventory database
 When I call POST /inventory/111/2
 Then I would create a new product "2" item with ID "111" 
 ```

**Comment by wsrong97** [comment]
As I am writing test cases for listing all the inventories for #6, I need the functionality of create an inventory to test none-empty inventory case, so I just wrote this one. Sorry about that.

**Comment by wsrong97** [comment]
I commented out my part and now uploaded the one with story #6
